sudo: required
dist: precise
language: c
compiler:
  - gcc
install:
  - sudo apt-get install dc gfortran doxygen flex bison pkg-config libncurses5-dev libexpat1-dev liblzma-dev libreadline-dev
  - curl --output /tmp/PIP-glibc.2018-08-28.tar.gz http://www.netbsd.org/~soda/PIP-glibc.2018-08-28.tar.gz
  - curl --output /tmp/PIP-417846d9.tar.gz http://www.netbsd.org/~soda/PIP-417846d9.tar.gz
  - sudo mkdir -p /usr/pip
  - ( cd /usr/pip && sudo tar pxf /tmp/PIP-glibc.2018-08-28.tar.gz )
  - ( cd /usr/pip && sudo tar pxf /tmp/PIP-417846d9.tar.gz )
before_script:
  - echo $TRAVIS_COMMIT
  - echo $TRAVIS_TAG
  - echo $TRAVIS_BRANCH
  - echo $TRAVIS_BUILD_NUMBER
  - echo $TRAVIS_REPO_SLUG
  - pwd
script:
  - sudo env EXTRA_CONFIGURE_OPTIONS="" EXTRA_GCC_OPTIONS="" ./build.sh --prefix=/usr/pip --with-glibc-libdir=/usr/pip/lib --with-pip=/usr/pip
